"""added image to patient

Revision ID: 208e91266c4c
Revises: 748185d9b598
Create Date: 2023-04-25 20:38:06.972084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208e91266c4c'
down_revision = '748185d9b598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
