"""more validation fun for procedure

Revision ID: 2943b70c48c5
Revises: e805ac1d0704
Create Date: 2023-05-03 11:39:32.047122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2943b70c48c5'
down_revision = 'e805ac1d0704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('service_line',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('service_line',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
