"""time elminated

Revision ID: 6d42f234a8ee
Revises: e4c0bfa1da84
Create Date: 2023-04-26 15:22:41.794510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d42f234a8ee'
down_revision = 'e4c0bfa1da84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('mrn',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('primary',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('surgeon',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('service_line',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('service_line',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('surgeon',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('primary',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('mrn',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
