"""more changes to checklist model

Revision ID: a4fc6c5cf13f
Revises: dc455f22ad9c
Create Date: 2023-05-07 14:48:01.754761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fc6c5cf13f'
down_revision = 'dc455f22ad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
