"""changes to checklist model

Revision ID: dc455f22ad9c
Revises: 36afe017d2ab
Create Date: 2023-05-07 12:54:24.677766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc455f22ad9c'
down_revision = '36afe017d2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_uploaded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('file_uploaded')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
